apiVersion: v1
kind: ConfigMap
metadata:
  name: gcr-auth-script
  namespace: argocd
data:
  gcr-auth.sh: |
    #!/bin/sh
    TOKEN=$(wget -qO- --header="Metadata-Flavor: Google" \
      "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" \
      | sed -n 's/.*"access_token":"\([^"]*\)".*/\1/p')
    echo "oauth2accesstoken:${TOKEN}"
