apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/stable/config/install.yaml
  - gcr-auth-script.yaml
  - image-updater.yaml
patches:
  - path: auth-script-patch.yaml
    target:
      kind: Deployment
      name: argocd-image-updater-controller
  - path: registries-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-image-updater-config
