apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yml
- ./../base
replacements:
- source:
    fieldPath: metadata.name
    kind: Service
    name: postgres-svc
  targets:
  - fieldPaths:
    - data.DATABASE_HOST
    select:
      kind: ConfigMap
      name: postgres-config
- source:
    fieldPath: metadata.name
    kind: Service
    name: todo-backend-svc
  targets:
  - fieldPaths:
    - data.BACKEND_HOST
    select:
      kind: ConfigMap
      name: backend-config
images:
- name: BROADCASTER_IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-501808/docker-images/broadcaster
  newTag: main-bbed15b8f265124d30eb2965ca628bdd79fdf25c
- name: TODO_APP_IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-501808/docker-images/todo-app
  newTag: main-bbed15b8f265124d30eb2965ca628bdd79fdf25c
- name: TODO_BACKEND_IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-501808/docker-images/todo-backend
  newTag: main-bbed15b8f265124d30eb2965ca628bdd79fdf25c
namespace: staging
namePrefix: stag-
