apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yml
- ./../base
- todo-backend/postgres-backup-cronjob.yml
patches:
- path: broadcaster/deployment.yml
- path: todo-backend/deployment.yml
replacements:
- source:
    fieldPath: metadata.name
    kind: Service
    name: postgres-svc
  targets:
  - fieldPaths:
    - data.DATABASE_HOST
    select:
      kind: ConfigMap
      name: postgres-config
- source:
    fieldPath: metadata.name
    kind: Service
    name: todo-backend-svc
  targets:
  - fieldPaths:
    - data.BACKEND_HOST
    select:
      kind: ConfigMap
      name: backend-config
images:
- name: BROADCASTER_IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-501808/docker-images/broadcaster
  newTag: prod-4.9
- name: TODO_APP_IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-501808/docker-images/todo-app
  newTag: prod-4.9
- name: TODO_BACKEND_IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-501808/docker-images/todo-backend
  newTag: prod-4.9
namespace: production
namePrefix: prod-
