apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: project
  annotations:
    # give ArgoCD instructions on how to prepare for this job
    # currently, at each sync, it runs in the second wave after
    # all other manifests and deletes the previous migration job
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: '1'
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-db
          image: busybox:1.38
          command:
            - sh
            - -c
            - | # test whether database is reachable at port 5432
              until nc -z -w2 "$DATABASE_HOST" 5432 2>/dev/null; do
                echo "Waiting for database..."
                sleep 2
              done
              echo 'Database reachable'
          envFrom:
            - configMapRef:
                name: postgres-config
      containers:
        - name: apply-db-migrations
          image: TODO_BACKEND_IMAGE
          command: ['npx', 'drizzle-kit', 'migrate']
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
